### PR TITLE
Fix delete message issue if text length is small

### LINKED ISSUE #57: User is not able to delete message if text length is small.
**Describe the bug**
User is not able to delete the message if the length of text message is small.
**To Reproduce**
Steps to reproduce the behaviour:
1. Join a room
2. Send a message 'Hi'
3. That's It

**Expected behaviour**

It should show delete message option regardless of length of characters

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

### PR DESCRIPTION
**Pull request by RituCs**
Fixes #57

#### Short description of what this resolves:
User able to delete message if text length is small

#### Changes proposed in this pull request

-
-
-

#### Checklist

- [x] My branch is up-to-date with the Upstream `development` branch.
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] I have added necessary documentation (if appropriate)

### CODE REVIEW

**Comment by RituCs** [comment]
Please Review this PR.

**Comment by Creatoon** [comment]
@RituCs add Screenshots of the output, and resolve the conflicts.

**Comment by RituCs** [comment]
> @RituCs add Screenshots of the output, and resolve the conflicts.

Screenshot from 2021-07-08 14-35-29
Conflicts Resolved @Creatoon

**Comment by RituCs** [comment]
Hey , @Creatoon  I have added the screenshot and also resolved the conflicts. So why this PR is not reviewed?

**Pull request merged**
