### PR TITLE
signup and login buttons are centered aligned

### PR DESCRIPTION
**Pull request by rajanandraj04**
the sign up and login buttons are centered aligned and also responsive for all type of screen resolution.

### CODE REVIEW

**Comment by Creatoon** [comment]
@rajanandraj04 As you have made changes in the style.css which is nice but the application uses style.min.css which is basically the minified version of style.css, so minify it first.

Add some screenshots to show your changes do work also verify once if your changes is not breaking any other layout.

Also mention which issue you are solving by using #issueNumber , it's a best practice.

**Comment by rajanandraj04** [comment]
Issue #70
style.css is minified and modified the style.min.css file,
 login and sign up buttons are centered.

please review it.

**Comment by Creatoon** [comment]
@rajanandraj04 that's great, you minified it and tagged the issue here,  just give the screenshot of the application, proving that your UI works, then I will gonna merge this PR

**Comment by rajanandraj04** [comment]
@Creatoon    can you help me for this , 

I am not familliar with pug files
and not able to run, plaese help me thorugh this....!

**Comment by Creatoon** [comment]
@rajanandraj04  have you tried each step of setup mentioned on docs ?

**Comment by rajanandraj04** [comment]
issue #70 
it seems perfect to me and 
here I attach the screenshot of the change.

jar

**Comment by Creatoon** [comment]
@rajanandraj04 please read the issue properly, it is written that - as the labels (email, name, password) are in the center, then the signup button in the bottom should also be in the center not the buttons in the navbar.

Here is the tip , you have to fix this on both pages which goes like /signup and /login, hope you understood.

**Pull request closed without merging**
