### PR TITLE
eadded: alt tag for the header just to improve accessibiliy of the app

### LINKED ISSUE #64: app accessibility
@Creatoon I want to work on some improvements for accessibility of the app listed by google lighthouse report.

### PR DESCRIPTION
**Pull request by oliashish**
Fixes #64 

#### Changes proposed in this pull request:

-
-
-

#### Checklist

- [x] My branch is up-to-date with the Upstream `development` branch.
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] I have added necessary documentation (if appropriate)

### CODE REVIEW

**Comment by Creatoon** [comment]
@oliashish Give screenshots of the pages after changes.
Also what have you done is, copied the code from style.css -> style.min.css

But this is not how , it is done.
Style.min.css is the minified version of style.css
You have to use minifier.
Because on our website we use min.css

**Comment by oliashish** [comment]
@Creatoon  yes the css one is because I haven't work with minified code therefore I did it on purpose to get a solution on how to do it from you when you review the code.
Also I have shared the screenshots in the issues section

**Comment by oliashish** [comment]
@Creatoon  just learnt about minifying, and I have done one can you please review it and let me know if that is it correct?

**Comment by Creatoon** [comment]
@oliashish Thanks For this Pr, you have learnt new things like minifying, it is necessary to make website fast, just read all the necessary things in the template, like this Fixes #<issueNumber>, branch is up to date checkbox, this is necessary so that we can review the pr asap.
Just be consistent.

**Pull request merged**
